package com.winlator.bridge;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;
import android.widget.Toast;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;

import com.winlator.MainActivity;
import com.winlator.R;
import com.winlator.XServerDisplayActivity;
import com.winlator.box64.Box64Preset;
import com.winlator.container.AudioDrivers;
import com.winlator.container.Container;
import com.winlator.container.ContainerManager;
import com.winlator.container.GraphicsDrivers;
import com.winlator.core.AppUtils;
import com.winlator.core.EnvVars;
import com.winlator.core.FileUtils;
import com.winlator.core.GPUHelper;
import com.winlator.core.KeyValueSet;
import com.winlator.core.PreloaderDialog;
import com.winlator.core.WineUtils;
import com.winlator.widget.FrameRating;
import com.winlator.xenvironment.RootFS;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.Executors;

/**
 * Exported entry point that lets DGPlayer (dsam3) launch a Windows game inside this container runtime.
 *
 * <p>Upstream Winlator has no external launch surface at all: {@code XServerDisplayActivity} is
 * {@code exported="false"} and {@code MainActivity} only accepts navigation extras. This activity is
 * the fork's contract — it resolves a shared container, imports the game payload once, applies the
 * per-game preset onto the container, and hands off to {@code XServerDisplayActivity}.
 *
 * <p>It deliberately does <em>not</em> write a {@code .desktop} shortcut. Winlator's {@code Shortcut}
 * parser reconstructs the executable path by string-slicing the {@code Exec=} line, which is fragile
 * to generate from the outside. Driving the container config directly is stable and
 * {@code XServerDisplayActivity} falls back to exactly those values when no shortcut is present.
 */
public class GameLaunchActivity extends AppCompatActivity {
    private static final String TAG = "DGPlayerBridge";

    // Must stay a literal mirroring AndroidManifest.xml (the manifest cannot reference BuildConfig).
    public static final String ACTION_PLAY_GAME = "com.retrople.action.PLAY_GAME";

    public static final String EXTRA_GAME_ID = "game_id";
    public static final String EXTRA_TITLE = "title";
    public static final String EXTRA_CONTENT_URI = "content_uri";
    public static final String EXTRA_EXE = "exe";
    public static final String EXTRA_EXE_ARGS = "exe_args";
    public static final String EXTRA_SCREEN_SIZE = "screen_size";
    public static final String EXTRA_GRAPHICS_DRIVER = "graphics_driver";
    public static final String EXTRA_DXWRAPPER = "dxwrapper";
    public static final String EXTRA_DXWRAPPER_CONFIG = "dxwrapper_config";
    public static final String EXTRA_BOX64_PRESET = "box64_preset";
    public static final String EXTRA_ENV_VARS = "env_vars";
    public static final String EXTRA_FORCE_FULLSCREEN = "force_fullscreen";
    /**
     * Fingerprint of everything this launch configures, so {@code XServerDisplayActivity} can tell
     * "the player pressed Play again" from "the player changed something and pressed Play".
     * Not part of the caller's contract - the bridge sets it for itself.
     */
    public static final String EXTRA_SESSION_KEY = "session_key";
    /**
     * Content URI of DGPlayer's per-game save archive, granted read + write. Optional: without it
     * the game still runs, it just keeps its in-game saves to itself. See {@link SaveSync}.
     */
    public static final String EXTRA_SAVE_URI = SaveSync.EXTRA_SAVE_URI;
    /**
     * A complete Input Controls profile (.icp JSON) generated by DGPlayer from the game's on-screen
     * pad layout. Takes precedence over the package's own {@code controlsProfile=} file so the
     * player can edit the layout in DGPlayer and see it here on the next launch.
     */
    public static final String EXTRA_CONTROLS_PROFILE = "controls_profile_json";
    /**
     * The full text of a {@code dgplayer.ini} the player edited in DGPlayer. When present it
     * replaces the archive's own file for this launch (see {@link GameManifest#applyOverride});
     * absent or blank means the archive's file applies again. Introduced in versionCode 32 —
     * DGPlayer gates sending it on that, older builds simply never see the extra.
     */
    public static final String EXTRA_MANIFEST_INI = "manifest_ini";

    /** Directory inside the container's C: drive that holds every game imported from DGPlayer. */
    public static final String GAMES_DIR = "DGPlayer";

    private static final String PREFS_NAME = "dgplayer_bridge";
    private static final String PREF_CONTAINER_ID = "container_id";
    private static final String CONTAINER_NAME = "DGPlayer";

    private final PreloaderDialog preloaderDialog = new PreloaderDialog(this);
    private final Handler handler = new Handler(Looper.getMainLooper());

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        AppUtils.setActivityTheme(this);
        super.onCreate(savedInstanceState);

        // May ask the user first, so everything after it runs from the callback.
        BridgeSecurity.authorize(this, allowed -> {
            if (allowed) onCallerAuthorized();
            else finishWithError("Caller not authorized");
        });
    }

    private void onCallerAuthorized() {
        final String gameId = sanitizeGameId(getIntent().getStringExtra(EXTRA_GAME_ID));
        if (gameId == null) {
            finishWithError("Missing or invalid game_id");
            return;
        }

        if (!RootFS.find(this).isValid()) {
            // First run of the fork itself. Installing the rootfs is MainActivity's job; sending the
            // user there is better than duplicating that flow inside the bridge.
            Toast.makeText(this, R.string.dgp_setup_required, Toast.LENGTH_LONG).show();
            startActivity(new Intent(this, MainActivity.class));
            finish();
            return;
        }

        preloaderDialog.show(R.string.starting_up);
        Executors.newSingleThreadExecutor().execute(() -> prepareAndLaunch(gameId));
    }

    /**
     * Maps the caller's game id onto a directory name that is safe both for the host filesystem and
     * for the DOS path it turns into.
     *
     * <p>Path separators would let the payload escape the container, and a space is just as bad in
     * practice: {@code XServerDisplayActivity.getWineStartCommand} emits the directory as an
     * unquoted {@code /dir <path>} argument, so a space there silently truncates the working
     * directory. Everything outside a conservative set collapses to an underscore, which is stable
     * across launches so the same game keeps resolving to the same directory.
     *
     * @return the sanitized id, or null if the input was missing or had nothing usable in it
     */
    private static String sanitizeGameId(String gameId) {
        if (gameId == null) return null;

        StringBuilder sanitized = new StringBuilder(gameId.length());
        for (int i = 0; i < gameId.length(); i++) {
            char c = gameId.charAt(i);
            boolean safe = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                    || (c >= '0' && c <= '9') || c == '-' || c == '_';
            sanitized.append(safe ? c : '_');
        }

        // An id of only underscores (or "..", which collapses to "__") carries no identity.
        String result = sanitized.toString();
        return result.replace("_", "").isEmpty() ? null : result;
    }

    private void prepareAndLaunch(String gameId) {
        ContainerManager containerManager = new ContainerManager(this);
        Container container = obtainContainer(containerManager);
        if (container == null) {
            finishWithErrorOnUiThread("Could not create container");
            return;
        }

        File gameDir = new File(container.getRootDir(), ".wine/drive_c/"+GAMES_DIR+"/"+gameId);
        Uri contentUri = getIntent().getParcelableExtra(EXTRA_CONTENT_URI);
        Uri saveUri = getIntent().getParcelableExtra(EXTRA_SAVE_URI);

        // A session that never reached exit() (crash, force-stop, battery) never exported its
        // saves. Catch up here, while the previous payload and its dgplayer.ini are both still in
        // place -- the reinstall below would take the in-folder saves with them.
        if (saveUri != null && SaveSync.hasPendingExport(this, gameId)) {
            SaveSync.exportOnExit(this, container, gameId, saveUri);
        }

        // Before anything can wipe the game dir (reinstall below), rescue the previous session's
        // log files to public Downloads. Every drive the container maps lives in app-private
        // storage, so this is the only way logs a guest program wrote (e.g. _inmm.log) can reach
        // adb or the user at all.
        exportDebugLogs(gameId, gameDir, new File(AppUtils.INTERNAL_STORAGE));

        // A repackaged zip under the same game id must win over the cached install, so the
        // installed check compares the payload's fingerprint, not mere marker existence.
        String fingerprint = contentUri != null ? PayloadInstaller.fingerprint(this, contentUri) : null;
        boolean payloadReinstalled = false;
        if (!PayloadInstaller.isInstalled(gameDir, fingerprint)) {
            if (contentUri == null) {
                finishWithErrorOnUiThread("Game not installed and no content_uri supplied");
                return;
            }

            preloaderDialog.showOnUiThread(R.string.dgp_installing_game);
            // A half-extracted directory would look installed on the next run; start from scratch.
            // This also wipes the previous payload's files (including anything it saved in its own
            // folder) — required, or the old and new game's files would merge unpredictably.
            PayloadInstaller.deleteRecursively(gameDir);
            if (!PayloadInstaller.install(this, contentUri, gameDir, fingerprint)) {
                PayloadInstaller.deleteRecursively(gameDir);
                finishWithErrorOnUiThread("Failed to import game payload");
                return;
            }
            payloadReinstalled = true;
            // The folder now holds exactly the package, which is the only moment its contents can
            // be told apart from the saves a game writes into it later.
            SaveSync.onPayloadInstalled(this, container, gameId);
        }

        // Settings ship inside the archive, but the player may have edited them in DGPlayer: that
        // text arrives as an extra and is materialized as a bridge-owned override file here — after
        // a possible reinstall wiped the folder, and before anything reads the manifest. Anything
        // the caller sent as an individual extra still overrides the resolved manifest below.
        String manifestSource = GameManifest.applyOverride(gameDir, getIntent().getStringExtra(EXTRA_MANIFEST_INI));
        Log.i(TAG, "manifest source="+manifestSource+" gameId="+gameId);
        GameManifest manifest = GameManifest.read(gameDir);

        String exe = resolve(EXTRA_EXE, manifest.get("exe"));
        if (exe == null) {
            finishWithErrorOnUiThread("No executable: pass the 'exe' extra or ship "+GameManifest.FILENAME);
            return;
        }

        File exeFile = new File(gameDir, exe);
        if (!exeFile.isFile()) {
            finishWithErrorOnUiThread("Executable not found: "+exe);
            return;
        }

        applyPreset(container, manifest, gameDir);
        applyCopies(container, manifest, gameDir);

        // After the payload (a reinstall would delete what we restore) and after applyPreset, whose
        // drives string is what resolves D: for the manifest copy targets. The executable check
        // above stays ahead of this on purpose: a game binary must come from the package, never
        // from a save archive.
        if (saveUri != null) {
            SaveSync.restoreIfNeeded(this, container, gameId, saveUri, manifest, payloadReinstalled);
        }

        // Everything below edits the prefix's registry hives as plain files, so it has to happen
        // while Wine is stopped — i.e. before XServerDisplayActivity starts.

        // Ahead of the per-game registry work: the prefix ships without Wine's own VfW codec
        // mappings, and a game whose cutscenes need one cannot start at all.
        VfwCodecs.ensureRegistered(container);

        String locale = localeOf(resolve(EXTRA_ENV_VARS, manifest.get("envVars")));
        if (locale != null) CjkFontSubstitutes.apply(container, locale);

        for (String regFile : manifest.getRegFiles()) {
            RegistryImporter.apply(container, new File(gameDir, regFile.replace('\\', '/')));
        }

        int controlsProfileId = importControlsProfile(manifest, gameDir);
        String[][] cdDiscs = prepareCdDiscs(manifest, gameDir);

        // XServerDisplayActivity splits arguments off the executable name when the file name contains
        // a space after its extension (see getWineStartCommand), so appending them here is enough.
        String execPath = exeFile.getAbsolutePath();
        String execArgs = resolve(EXTRA_EXE_ARGS, manifest.get("args"));
        if (execArgs != null) execPath += " "+execArgs;

        boolean forceFullscreen = getIntent().hasExtra(EXTRA_FORCE_FULLSCREEN)
                ? getIntent().getBooleanExtra(EXTRA_FORCE_FULLSCREEN, false)
                : manifest.getBoolean("forceFullscreen");

        // As late as possible, so every file the bridge itself just wrote counts as pre-existing.
        if (saveUri != null) SaveSync.beginSession(this, container, gameId, manifest);

        Intent intent = new Intent(this, XServerDisplayActivity.class);
        intent.putExtra("container_id", container.id);
        intent.putExtra("exec_path", execPath);
        // Identifies the session this launch would produce. The manifest text is in here because
        // the container knobs it sets (screen size, graphics driver, box64 preset, env vars...)
        // are applied to the shared container above and are invisible in the intent itself.
        intent.putExtra(EXTRA_SESSION_KEY, sessionKey(gameId, execPath,
                GameManifest.rawText(gameDir), String.valueOf(controlsProfileId),
                String.valueOf(forceFullscreen), Arrays.deepToString(cdDiscs)));
        // Tells XServerDisplayActivity.exit() to finish instead of restarting into MainActivity.
        intent.putExtra("from_bridge", true);
        // XServerDisplayActivity.exit() is where a session ends, so that is where saves are
        // exported. It needs the sanitized id (not DGPlayer's file name) to find the state file.
        intent.putExtra(SaveSync.EXTRA_GAME_ID, gameId);
        if (saveUri != null) intent.putExtra(EXTRA_SAVE_URI, saveUri);
        if (controlsProfileId > 0) {
            intent.putExtra("controls_profile", controlsProfileId);
            // Only meaningful for a profile DGPlayer sent: the URI names one entry of its library.
            Uri controlsReturnUri = getIntent().getParcelableExtra(ControlsReturn.EXTRA_CONTROLS_RETURN_URI);
            if (controlsReturnUri != null) intent.putExtra(ControlsReturn.EXTRA_CONTROLS_RETURN_URI, controlsReturnUri);
        }
        intent.putExtra("force_fullscreen", forceFullscreen);
        if (cdDiscs != null) {
            intent.putExtra("cd_paths", cdDiscs[0]);
            intent.putExtra("cd_labels", cdDiscs[1]);
        }

        handler.post(() -> {
            preloaderDialog.close();
            startActivity(intent);
            finish();
        });
    }

    /**
     * SHA-256 of the given parts, hex. Only equality matters, and a hash keeps the intent small
     * however large the manifest grows.
     */
    private static String sessionKey(String... parts) {
        StringBuilder sb = new StringBuilder();
        for (String part : parts) sb.append(part == null ? "" : part).append('\0');
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256")
                    .digest(sb.toString().getBytes(StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder(digest.length * 2);
            for (byte b : digest) hex.append(String.format("%02x", b));
            return hex.toString();
        }
        catch (NoSuchAlgorithmException e) {
            // Every Android release ships SHA-256; fall back to the raw text rather than failing
            // the launch, which only costs a bigger extra.
            return sb.toString();
        }
    }

    /**
     * Returns the single container shared by every DGPlayer game, creating it on first use.
     * One container per game would multiply a 1.5-3 GB wineprefix by the size of the library; games
     * are isolated by directory instead, and per-game settings ride on the container config.
     */
    private Container obtainContainer(ContainerManager containerManager) {
        SharedPreferences preferences = getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE);
        int containerId = preferences.getInt(PREF_CONTAINER_ID, -1);

        if (containerId != -1) {
            Container container = containerManager.getContainerById(containerId);
            if (container != null) return container;
            // The user deleted it from the Containers screen; fall through and make a new one.
        }

        Container container = createContainerSync(containerManager);
        if (container != null) {
            preferences.edit().putInt(PREF_CONTAINER_ID, container.id).apply();
        }
        return container;
    }

    /**
     * ContainerManager only exposes an async creator that posts its callback to a Handler, so this
     * bridges it back to the calling (background) thread.
     */
    private Container createContainerSync(ContainerManager containerManager) {
        final Container[] result = new Container[1];
        final Object lock = new Object();
        final boolean[] done = {false};

        try {
            JSONObject data = new JSONObject();
            data.put("name", CONTAINER_NAME);
            // Every other property is left out on purpose: Container.loadData only overwrites keys
            // that are present, so omitted ones keep their upstream defaults.

            handler.post(() -> containerManager.createContainerAsync(data, (container) -> {
                synchronized (lock) {
                    result[0] = container;
                    done[0] = true;
                    lock.notifyAll();
                }
            }));
        }
        catch (JSONException e) {
            return null;
        }

        synchronized (lock) {
            long deadline = System.currentTimeMillis() + 300000;
            while (!done[0]) {
                long remaining = deadline - System.currentTimeMillis();
                if (remaining <= 0) return null;
                try {
                    lock.wait(remaining);
                }
                catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    return null;
                }
            }
        }
        return result[0];
    }

    /**
     * Resolves the on-screen controls profile (.icp) for this launch and returns its profile id
     * (0 if there is none).
     *
     * <p>DGPlayer's own VPAD overlay cannot reach a game running in this app, so touch controls have
     * to come from Winlator's InputControls system instead. Two sources feed it: the layout DGPlayer
     * generates from the game's pad (sent as {@link #EXTRA_CONTROLS_PROFILE}) and, as a fallback, an
     * .icp the package itself ships via the {@code controlsProfile} manifest key. The generated one
     * wins — the player edits it there, so a stale file inside the archive must not shadow it.
     *
     * <p>Storage is {@link BridgeControlsProfiles#upsert}'s job: matched by name, overwritten in
     * place, id preserved.
     */
    private int importControlsProfile(GameManifest manifest, File gameDir) {
        // DGPlayer's generated layout wins over whatever the package ships: the player edits it
        // there, so a stale file inside the archive must not shadow it.
        String json = getIntent().getStringExtra(EXTRA_CONTROLS_PROFILE);
        String source = "intent";

        if (json == null || json.isEmpty()) {
            String relativePath = manifest.get("controlsProfile");
            if (relativePath == null || relativePath.isEmpty()) return 0;

            File icpFile = new File(gameDir, relativePath.replace('\\', '/'));
            if (!icpFile.isFile()) {
                Log.w(TAG, "controls profile missing from package: "+relativePath);
                return 0;
            }
            json = FileUtils.readString(icpFile);
            source = relativePath;
        }

        try {
            return BridgeControlsProfiles.upsert(this, new JSONObject(json), source);
        }
        catch (JSONException e) {
            Log.w(TAG, "bad controls profile "+source, e);
            return 0;
        }
    }

    /**
     * Copies the previous session's {@code *.log} files from the container-visible directories
     * into public {@code Download/WinRunner}, where adb and the user can actually reach them.
     * Guest programs (like the {@code _inmm} audio shim) can only write inside the app-private
     * drives, so without this hop their diagnostics are unreadable from outside.
     *
     * <p>Runs before a possible payload reinstall wipes the game dir. Best-effort by design: a
     * missing storage permission must never block a launch.
     */
    private void exportDebugLogs(String gameId, File... sourceDirs) {
        try {
            File exportDir = new File(Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_DOWNLOADS), "WinRunner");
            for (File dir : sourceDirs) {
                File[] logs = dir.listFiles((d, name) -> name.toLowerCase(Locale.ENGLISH).endsWith(".log"));
                if (logs == null) continue;
                for (File log : logs) {
                    if (!exportDir.isDirectory() && !exportDir.mkdirs()) {
                        Log.w(TAG, "cannot create log export dir "+exportDir);
                        return;
                    }
                    File target = new File(exportDir, gameId+"-"+log.getName());
                    if (FileUtils.copy(log, target)) Log.i(TAG, "exported log to "+target);
                    else Log.w(TAG, "failed to export log "+log);
                }
            }
        }
        catch (Exception e) {
            Log.w(TAG, "log export failed", e);
        }
    }

    /**
     * Validates the manifest's {@code cd=} entries and stamps each disc folder with the
     * {@code .windows-label}/{@code .windows-serial} files Wine reads as the volume label and
     * serial of a directory-backed cdrom drive.
     *
     * <p>Games see a single CD-ROM drive, the way a real PC ran multi-disc titles:
     * {@code XServerDisplayActivity} points X: at the first disc before Wine starts and re-points
     * the {@code dosdevices/x:} symlink when the user swaps discs from the in-game drawer menu.
     *
     * @return {paths[], labels[]} for the launch intent, or null when the manifest declares no
     *         usable disc
     */
    private String[][] prepareCdDiscs(GameManifest manifest, File gameDir) {
        List<String[]> cds = manifest.getCds();
        if (cds.isEmpty()) return null;

        List<String> paths = new ArrayList<>();
        List<String> labels = new ArrayList<>();
        for (String[] cd : cds) {
            File dir = new File(gameDir, cd[0].replace('\\', '/'));
            try {
                // Same guard as the payload extraction: the manifest is attacker-controlled text
                // and a disc path must not reach outside the game's own folder.
                if (!dir.getCanonicalPath().startsWith(gameDir.getCanonicalPath()+File.separator)
                        || !dir.isDirectory()) {
                    Log.w(TAG, "skipping cd entry, unusable: "+cd[0]);
                    continue;
                }
            }
            catch (IOException e) {
                Log.w(TAG, "skipping cd entry, unresolvable: "+cd[0], e);
                continue;
            }

            String label = cd[1] != null ? cd[1] : dir.getName();
            FileUtils.writeString(new File(dir, ".windows-label"), label+"\n");
            // Distinct serials per disc, so a game that remembers discs by serial can tell them
            // apart. Same format WineUtils uses for the container's stock drive_x.
            String serial = String.format(Locale.ENGLISH, "%-8x", (int)'X'+paths.size()).replace(' ', '0');
            FileUtils.writeString(new File(dir, ".windows-serial"), serial+"\n");

            paths.add(dir.getAbsolutePath());
            labels.add(label);
        }

        if (paths.isEmpty()) return null;
        return new String[][]{paths.toArray(new String[0]), labels.toArray(new String[0])};
    }

    /**
     * Copies files the package wants placed outside its own folder — typically settings the original
     * installer would have written into {@code C:\windows}.
     */
    private void applyCopies(Container container, GameManifest manifest, File gameDir) {
        for (String[] copy : manifest.getCopies()) {
            File source = new File(gameDir, copy[0].replace('\\', '/'));
            String destination = WineUtils.dosToUnixPath(copy[1], container);

            if (!source.isFile() || destination.isEmpty()) {
                Log.w(TAG, "skipping copy, unusable: "+copy[0]+" -> "+copy[1]);
                continue;
            }
            // Guard the same way the payload extraction does: a copy target is attacker-controlled
            // text, and dosToUnixPath happily resolves anything the drive table can reach.
            File destinationFile = new File(destination);
            if (!FileUtils.copy(source, destinationFile)) {
                Log.w(TAG, "copy failed: "+source+" -> "+destinationFile);
                continue;
            }
            FileUtils.chmod(destinationFile, 0771);
        }
    }

    /**
     * Writes the per-game preset onto the shared container.
     *
     * <p>Every managed field is written on every launch — anything the package leaves unset is reset
     * to the Winlator default rather than inherited. One container is shared by the whole library, so
     * "leave it alone if unspecified" means the previous game's settings silently apply to the next
     * one. That bit once already: a package that set {@code dxwrapper=cnc-ddraw} left the field set
     * for the following game, and because {@code DXWrappers.parseConfigs} only honours a config when
     * {@code dxwrapper} is dxvk or wined3d, that game's {@code ddrawWrapper} was quietly discarded.
     */
    private void applyPreset(Container container, GameManifest manifest, File gameDir) {
        boolean changed = false;

        // Point D: at this game's folder. DOSP95 shipped these titles as disk images that DOSBox
        // mounted as D:, so anything converted from one still refers to itself as D:\<Game>.
        // Safe against the fragile drives parser (it splits on ':') because the container path has
        // no colon in it; E: keeps its default so the app storage drive stays reachable.
        String drives = "D:"+gameDir.getAbsolutePath()+"E:"+AppUtils.INTERNAL_STORAGE;
        if (!drives.equals(container.getDrives())) {
            container.setDrives(drives);
            changed = true;
        }

        String screenSize = or(resolve(EXTRA_SCREEN_SIZE, manifest.get("screenSize")), Container.DEFAULT_SCREEN_SIZE);
        if (!screenSize.equals(container.getScreenSize())) {
            container.setScreenSize(screenSize);
            changed = true;
        }

        // Vulkan follows upstream's device detection (Adreno -> turnip, else vortek). The GL half
        // deliberately deviates from upstream's gladio default: on Adreno 830 / Android 16 gladio
        // maps windows but presents nothing — every GL-backed game (all DirectDraw wrappers included)
        // came up as a black screen with working audio, while the same game rendered the moment the
        // GL driver was switched to zink (GL-over-Vulkan). Verified 2026-08-17, 환세취호전/HWANSE.EXE.
        String defaultDriver = (GPUHelper.getAdrenoModelId(this) > 0
                ? GraphicsDrivers.TURNIP : GraphicsDrivers.DEFAULT_VULKAN_DRIVER)
                +","+GraphicsDrivers.ZINK;
        String graphicsDriver = or(resolve(EXTRA_GRAPHICS_DRIVER, manifest.get("graphicsDriver")), defaultDriver);
        if (!graphicsDriver.equals(container.getGraphicsDriver())) {
            container.setGraphicsDriver(graphicsDriver);
            changed = true;
        }

        // The Direct3D wrapper only. The DirectDraw one is a key inside dxwrapperConfig below —
        // and putting anything but dxvk/wined3d here makes DXWrappers.parseConfigs drop that config
        // on the floor, so never let a package's stray value survive into the next launch.
        String dxwrapper = or(resolve(EXTRA_DXWRAPPER, manifest.get("dxwrapper")), Container.DEFAULT_DXWRAPPER);
        if (!dxwrapper.equals(container.getDXWrapper())) {
            container.setDXWrapper(dxwrapper);
            changed = true;
        }

        // Comma-separated k=v. Holds "ddrawWrapper" (default wined3d), which is what a 90s
        // DirectDraw game actually renders through — wined3d needs GL, so on a Vulkan-only
        // container it draws nothing and the game looks like a black screen with sound.
        String dxwrapperConfig = or(resolve(EXTRA_DXWRAPPER_CONFIG, manifest.get("dxwrapperConfig")), "");
        if (!dxwrapperConfig.equals(container.getDXWrapperConfig())) {
            container.setDXWrapperConfig(dxwrapperConfig);
            changed = true;
        }

        String box64Preset = or(resolve(EXTRA_BOX64_PRESET, manifest.get("box64Preset")), Box64Preset.DEFAULT);
        if (!box64Preset.equals(container.getBox64Preset())) {
            container.setBox64Preset(box64Preset);
            changed = true;
        }

        // Merged onto the defaults rather than replacing them: those carry the Mesa/Zink/esync
        // settings the renderer depends on, and a game that only wants to set a locale would
        // otherwise silently turn them all off.
        EnvVars envVars = new EnvVars(Container.DEFAULT_ENV_VARS);
        String extraEnvVars = resolve(EXTRA_ENV_VARS, manifest.get("envVars"));
        if (extraEnvVars != null) envVars.putAll(new EnvVars(extraEnvVars));
        if (!envVars.toString().equals(container.getEnvVars())) {
            container.setEnvVars(envVars.toString());
            changed = true;
        }

        // Manifest-only knobs (no intent extra of their own — the edited manifest text already
        // travels whole in EXTRA_MANIFEST_INI). Same rule as above: unset means Winlator default.
        byte startupSelection = parseStartupSelection(manifest.get("startupSelection"));
        if (startupSelection != container.getStartupSelection()) {
            container.setStartupSelection(startupSelection);
            changed = true;
        }

        // Merged onto the defaults like envVars: a package that only needs directshow=1 must not
        // switch every other component off. XServerDisplayActivity compares the result with the
        // components it last extracted and only re-extracts DLLs when the set actually changed.
        String wincomponents = mergeWinComponents(manifest.get("wincomponents"));
        if (!wincomponents.equals(container.getWinComponents())) {
            container.setWinComponents(wincomponents);
            changed = true;
        }

        String audioDriver = manifest.get("audioDriver");
        if (!AudioDrivers.ALSA.equals(audioDriver) && !AudioDrivers.PULSEAUDIO.equals(audioDriver)) {
            audioDriver = Container.DEFAULT_AUDIO_DRIVER;
        }
        if (!audioDriver.equals(container.getAudioDriver())) {
            container.setAudioDriver(audioDriver);
            changed = true;
        }

        byte hudMode = parseShowFps(manifest.get("showFPS"));
        if (hudMode != container.getHUDMode()) {
            container.setHUDMode(hudMode);
            changed = true;
        }

        if (changed) container.saveData();
    }

    /** {@code startupSelection=0|1|2} (normal / essential / aggressive); anything else = essential. */
    private static byte parseStartupSelection(String value) {
        if (value == null) return Container.STARTUP_SELECTION_ESSENTIAL;
        try {
            byte selection = Byte.parseByte(value.trim());
            if (selection == Container.STARTUP_SELECTION_NORMAL
                    || selection == Container.STARTUP_SELECTION_ESSENTIAL
                    || selection == Container.STARTUP_SELECTION_AGGRESSIVE) return selection;
        }
        catch (NumberFormatException ignored) {}
        Log.w(TAG, "ignoring unknown startupSelection: "+value);
        return Container.STARTUP_SELECTION_ESSENTIAL;
    }

    /**
     * {@code showFPS=0|1|2} maps onto {@link FrameRating.Mode} (disabled / simple / full);
     * {@code true} is the simple HUD. Anything else = disabled.
     */
    private static byte parseShowFps(String value) {
        if (value == null) return (byte)FrameRating.Mode.DISABLED.ordinal();
        String v = value.trim();
        if (v.equals("1") || v.equalsIgnoreCase("true")) return (byte)FrameRating.Mode.SIMPLE.ordinal();
        if (v.equals("2")) return (byte)FrameRating.Mode.FULL.ordinal();
        if (!v.equals("0") && !v.equalsIgnoreCase("false")) Log.w(TAG, "ignoring unknown showFPS: "+value);
        return (byte)FrameRating.Mode.DISABLED.ordinal();
    }

    /**
     * Overlays the manifest's {@code wincomponents} pairs onto {@link Container#DEFAULT_WINCOMPONENTS}.
     * Only keys the container already knows are accepted, so a typo cannot introduce a component
     * name {@code extractWinComponentFiles} has no archive for.
     */
    private static String mergeWinComponents(String value) {
        KeyValueSet merged = new KeyValueSet(Container.DEFAULT_WINCOMPONENTS);
        if (value == null || value.trim().isEmpty()) return merged.toString();

        for (String pair : value.split(",")) {
            int eq = pair.indexOf('=');
            if (eq <= 0) continue;
            String key = pair.substring(0, eq).trim();
            String v = pair.substring(eq+1).trim();
            if (key.isEmpty() || merged.get(key, null) == null) {
                Log.w(TAG, "ignoring unknown wincomponent: "+pair);
                continue;
            }
            boolean enabled = v.equals("1") || v.equalsIgnoreCase("true");
            merged.put(key, enabled ? "1" : "0");
        }
        return merged.toString();
    }

    /** Pulls {@code LC_ALL}/{@code LANG} out of an env var string, or null if neither is set. */
    private static String localeOf(String envVars) {
        if (envVars == null) return null;
        for (String token : envVars.split("\\s+")) {
            int eq = token.indexOf('=');
            if (eq <= 0) continue;
            String name = token.substring(0, eq);
            if (name.equals("LC_ALL") || name.equals("LANG")) return token.substring(eq+1);
        }
        return null;
    }

    private static String or(String value, String fallback) {
        return value != null ? value : fallback;
    }

    /** Intent extra if the caller sent a non-blank one, else the archive's value, else null. */
    private String resolve(String extraName, String manifestValue) {
        String value = getIntent().getStringExtra(extraName);
        if (value == null || value.trim().isEmpty()) value = manifestValue;
        if (value == null) return null;
        value = value.trim();
        return value.isEmpty() ? null : value;
    }

    private void finishWithError(String message) {
        // Also logged: a Toast is useless to whatever is driving this activity, and every rejection
        // here otherwise looks identical from the outside (activity opens, closes, nothing happens).
        Log.e(TAG, message);
        Toast.makeText(this, message, Toast.LENGTH_LONG).show();
        setResult(Activity.RESULT_CANCELED);
        finish();
    }

    private void finishWithErrorOnUiThread(String message) {
        handler.post(() -> {
            preloaderDialog.close();
            finishWithError(message);
        });
    }
}
